<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPe4ym1Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPe4ym1Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPe4ym1Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPe4ym1Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPe4ym1Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'Pe4ym1Q',
    'container.build_id' => '3d0a277c',
    'container.build_time' => 1655190217,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPe4ym1Q');
