<?php

namespace ContainerPe4ym1Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7BiKyEGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7BiKyEG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7BiKyEG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'guestBook' => ['privates', '.errored..service_locator.7BiKyEG.App\\Entity\\Guest', NULL, 'Cannot autowire service ".service_locator.7BiKyEG": it references class "App\\Entity\\Guest" but no such service exists.'],
        ], [
            'guestBook' => 'App\\Entity\\Guest',
        ]);
    }
}
