<?php

namespace ContainerPe4ym1Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGuestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7BiKyEG.App\Entity\Guest' shared service.
     *
     * @return \App\Entity\Guest
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7BiKyEG": it references class "App\\Entity\\Guest" but no such service exists.');
    }
}
